title: Raycast Daily Planner Extension
description: >- # this means to ignore newlines until "baseurl:"
  The Raycast Daily Planner extension documentation site offers in-depth
  guidance on using this powerful productivity tool for time blocking, time
  tracking, and time usage analysis on macOS.
baseurl: "/docs" # the subpath of your site, e.g. /blog
url: "https://benyn.github.io"
github_username: benyn

# Build settings
theme: just-the-docs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
